name = 'rain'
license = 'MIT'
licenselink = 'https://github.com/rainto0322/hugo-theme-rain/main/LICENSE'
description = '🌷 A tiny hugo theme .'

[Language]
  LanguageCode = 'zh-CN'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/rainto0322/hugo-theme-rain'

# If you have a running demo of the theme
demosite = 'https://rainto.top'

# Taxonomy terms
tags = ['blog', 'tini', 'minimal', 'simple', 'code' ]
features = ['some', 'tini', 'features']

# If the theme has a single author
[author]
  name = 'Rainto'
  homepage = 'https://github.com/rainto0322'